package cmd

import (
	"fmt"
	"github.com/ebrahimahmadi/ar-cli/pkg/config"
	"github.com/spf13/cobra"
)

var (
	authDesc = ` Log in to Arvan API and save login for subsequent use
    First-time users of the client should run this command to connect to a Arvan API,
    establish an authenticated session, and save connection to the configuration file.`
)

var ApiKey string

var authCmd = &cobra.Command{
	Use:   "auth",
	Short: "Log in to Arvan server",
	Long:  authDesc,
	Run: func(cmd *cobra.Command, args []string) {
		arvanConfig := config.GetConfigInfo()
		
		arvanConfig.SetApiKey(ApiKey)

		arvanConfig.SaveConfig()

		fmt.Println("Configuration saved successfully.")
	},
}

func init() {
	rootCmd.AddCommand(authCmd)
	authCmd.Flags().StringVarP(&ApiKey, "key", "k", "", "Api Key generated by Arvan")
}
