name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: |
          go build
      - name: Style
        run: go fmt ./...
      - name: publish bins to master
        run: |
          git config --global user.name 'ebrahimahmadi'
          git config --global user.email 'eahmadi641@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout main
          git add .
          git commit -am "feat(bin): add bin file"
          git push
